root: true
env:
  browser: true
  es2021: true
  webextensions: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-recommended'
  - '@vue/typescript/recommended'
  - 'prettier'
  - 'plugin:prettier/recommended'
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
plugins:
  - vue
  - '@typescript-eslint'
rules:
  'vue/no-v-model-argument': 'off'
  'comma-dangle': 'off'
  '@typescript-eslint/comma-dangle': ['error', 'only-multiline']
